out_dir_path: "E:\\out\\simclr"
batch_size: 128
epochs: 80
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
lr: 1e-3
weight_decay: 10e-6
fp16_precision: False

model:
  out_dim: 256
  base_model: "resnet18"

dataset:
  data_path: "E:\\data\\cat-vs-dog\\cat"
  color_scale: 1
  input_shape: (96,96,3)
  num_workers: 0
  valid_size: 0.05

loss:
  temperature: 0.5
  use_cosine_similarity: True
